
CONFIG_FILE_PATH = "config.yaml"

PROPERTY_NAME_NETWORK = "network"
PROPERTY_NAME_HOST = "host"
PROPERTY_NAME_PORT = "port"
PROPERTY_NAME_DRIVER_NAME = "driver_name"
PROPERTY_NAME_USER = "user"
PROPERTY_NAME_PASSWORD = "password"
PROPERTY_NAME_DB_NAME = "db_name"
PROPERTY_NAME_SSL_MODE = "ssl_mode"
PROPERTY_NAME_SERVICE = "service"
PROPERTY_NAME_DATABASE = "database"

SOURCE_SERVICE = "service"
SOURCE_DATABASE = "database"

DEFAULT_POSTGRESQL_PORT = "5432"